name: Test deploy to K3s

on:
  workflow_dispatch:
  push:
    branches:
      - k3s-deploy
    paths:
      - __about__.py

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up K3s kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Update Kubernetes Deployment
        run: |
          kubectl -n tp auth can-i patch deployments
          kubectl -n tp auth can-i list pods

      - name: Update Kubernetes Deployment
        run: |
          kubectl -n tp set image deployment/api-turplanlegger-api turplanlegger-api=ghcr.io/turplanlegger/turplanlegger-api:sha-cd3ec201f515a2fe4e29817b5f7311b6e0deae6e
          kubectl rollout status deployment/api-turplanlegger-api